import React from "react";

const Rules = () => {
  return (
    <div className="container my-5">
      <div className="card shadow">
        <h3 className="text-center mb-4 fw-bold">
          OFFICIAL RULES — 50/50 RAFFLE
          <br />
          <small className="text-muted">TICKET PLUS, INC.</small>
        </h3>
        <div
          className="card-body p-4"
          style={{ height: "420px", overflowY: "auto" }}
        >
          <div className="rules-content" style={{ whiteSpace: "pre-line" }}>
            <h6 className="fw-bold mt-4">1. LEGAL AUTHORITY AND COMPLIANCE</h6>
            THIS 50/50 RAFFLE (“RAFFLE”) IS CONDUCTED PURSUANT TO LAW NO. 465 OF
            MAY 15, 1947, WHICH CREATED THE PUERTO RICO LOTTERY, DACO REGULATION
            NO. 7764 ON SWEEPSTAKES, AND REGULATION NO. 9158 ON COMMERCIAL
            PRACTICES. TICKET PLUS, INC. ENSURES COMPLIANCE WITH THESE
            APPLICABLE LAWS AND REGULATIONS, INTERPRETED IN FAVOR OF THE
            CONSUMER.
            <h6 className="fw-bold mt-4">2. ORGANIZING ENTITY</h6>
            THE RAFFLE IS ORGANIZED AND ADMINISTERED BY TICKET PLUS, INC., A
            CORPORATION DULY AUTHORIZED TO OPERATE IN PUERTO RICO. ALL OFFICIAL
            COMMUNICATIONS SHALL BE DIRECTED TO TICKET PLUS, INC. THROUGH ITS
            OFFICIAL WEBSITE OR REGISTERED POSTAL ADDRESS.
            <h6 className="fw-bold mt-4">3. PURPOSE AND 50/50 STRUCTURE</h6>
            THE PURPOSE OF THIS RAFFLE IS TO RAISE FUNDS THROUGH A 50/50
            DRAWING, IN WHICH FIFTY PERCENT (50%) OF THE TOTAL GROSS PROCEEDS
            (“GROSS FUND”) WILL BE AWARDED TO THE WINNER, AND THE REMAINING
            FIFTY PERCENT (50%) WILL BE DONATED TO AN ENTITY DETERMINED BY THE
            CLIENT CONTRACTING TICKET PLUS, INC.’S SERVICES. ANY VISUAL
            REPRESENTATIONS OF PRIZES OR AMOUNTS ARE ILLUSTRATIVE AND MUST
            REFLECT THE ACTUAL CHARACTERISTICS AND CALCULATION OF THE FINAL
            GROSS RAFFLE FUND AT DRAW TIME.
            <h6 className="fw-bold mt-4">4. ELIGIBILITY</h6>
            PARTICIPATION IS OPEN TO INDIVIDUALS AGED 18 OR OLDER WHO ARE
            RESIDENTS OF OR PHYSICALLY PRESENT IN PUERTO RICO AT THE TIME OF
            TICKET PURCHASE. EMPLOYEES, AFFILIATES, AND IMMEDIATE FAMILY MEMBERS
            OF TICKET PLUS, INC., AS WELL AS PUBLIC OFFICIALS WITH AUTHORITY
            OVER SWEEPSTAKES REGULATION, ARE NOT ELIGIBLE. PARTICIPATION
            CONSTITUTES ACCEPTANCE OF THESE OFFICIAL RULES AND THE EXCLUSIVE
            JURISDICTION OF PUERTO RICO. PARTICIPANTS MUST PROVIDE ACCURATE
            REGISTRATION INFORMATION AND MAY BE REQUIRED TO VERIFY IDENTITY AND
            ELIGIBILITY.
            <h6 className="fw-bold mt-4">5. ENTRY METHOD</h6>
            TICKETS MAY BE PURCHASED IN PERSON OR THROUGH AUTHORIZED DIGITAL
            CHANNELS. PRICES ARE AS FOLLOWS: 1 TICKET FOR $10, 5 FOR $20, 25 FOR
            $40, AND 100 FOR $100. NO PURCHASE IS NECESSARY TO ENTER; A FREE
            ALTERNATIVE METHOD OF ENTRY (AMOE) WILL BE AVAILABLE IN ACCORDANCE
            WITH RULE 5(21) OF REGULATION 7764. ENTRIES RECEIVED VIA AMOE ARE
            TREATED THE SAME AS PAID ENTRIES. IN CASE OF IDENTITY DISPUTES, THE
            “AUTHORIZED ACCOUNT HOLDER” OR THE PERSON WHOSE NAME APPEARS ON THE
            ENTRY (OR AMOE SUBMISSION) MAY BE DEEMED THE ENTRANT, SUBJECT TO
            PROOF AS REQUIRED.
            <h6 className="fw-bold mt-4">
              6. RAFFLE PERIOD; EXTENSIONS; SHORTFALLS
            </h6>
            EACH RAFFLE WILL HAVE A DEFINED ENTRY PERIOD, WHICH WILL BE PUBLICLY
            ANNOUNCED IN ADVANCE THROUGH OFFICIAL AND AUTHORIZED MEDIA. NO
            TICKETS SHALL BE ISSUED ONCE THE OFFICIAL ENTRY PERIOD HAS ENDED.
            THERE WILL NOT BE A FUNDRAISING GOAL. ANY EXTENSIONS OR
            CANCELLATIONS WILL BE COMMUNICATED VIA THE SAME CHANNELS WHERE THE
            RULES WERE POSTED.
            <h6 className="fw-bold mt-4">7. PRIZE</h6>
            THE WINNER WILL RECEIVE FIFTY PERCENT (50%) OF THE GROSS FUND. IF
            THE PRIZE IS NOT CLAIMED WITHIN NINETY (90) CALENDAR DAYS, IT WILL
            BE DONATED TO A CHARITABLE CAUSE. PAYMENT WILL BE MADE VIA CHECK OR
            TRANSFER UPON IDENTITY VERIFICATION. THE ODDS OF WINNING DEPEND ON
            THE NUMBER OF VALID ENTRIES RECEIVED. UNLESS OTHERWISE REQUIRED BY
            LAW, THE PRIZE IS NOT TRANSFERABLE AND IS NOT PAYABLE IN ANY FORM
            OTHER THAN AS STATED. THE WINNER IS RESPONSIBLE FOR ANY APPLICABLE
            PUERTO RICO TAXES, FEES, OR WITHHOLDINGS.
            <h6 className="fw-bold mt-4">8. WINNER SELECTION</h6>
            THE WINNING TICKET NUMBER WILL BE SELECTED AT RANDOM USING A
            CERTIFIED ELECTRONIC SYSTEM UNDER THE SUPERVISION OF AN AUTHORIZED
            REPRESENTATIVE. RESULTS WILL BE PUBLICLY ANNOUNCED ON TICKET PLUS,
            INC.’S OFFICIAL WEBSITE AND SOCIAL MEDIA ACCOUNTS. THE ODDS OF
            WINNING DEPEND ON THE NUMBER OF VALID ENTRIES RECEIVED.
            <h6 className="fw-bold mt-4">9. NOTIFICATION AND CLAIM PROCESS</h6>
            TICKET PLUS WILL ATTEMPT TO NOTIFY THE POTENTIAL WINNER USING THE
            CONTACT INFORMATION PROVIDED AT REGISTRATION/ENTRY. TO CLAIM, THE
            POTENTIAL WINNER MUST FOLLOW THE INSTRUCTIONS IN THE NOTIFICATION
            AND PROVIDE A VALID GOVERNMENT-ISSUED PHOTO ID, AND SIGN AN
            ACCEPTANCE/RELEASE OF LIABILITY AND PUBLICITY AUTHORIZATION. IF THE
            WINNER DOES NOT COMPLETE THE CLAIM WITHIN THE TIME STATED IN THE
            ABBREVIATED RULES THE PRIZE MAY BE FORFEITED.
            <h6 className="fw-bold mt-4">10. ADVERTISING AND DISCLOSURE</h6>
            OFFICIAL RULES WILL BE AVAILABLE ON THE OFFICIAL WEBSITE AND AT ALL
            AUTHORIZED SALES POINTS. ALL ADVERTISEMENTS WILL INCLUDE THE
            ORGANIZER’S NAME, RAFFLE DATE, FREE ENTRY METHOD, AND REFERENCE TO
            WHERE THE FULL RULES CAN BE ACCESSED, IN ACCORDANCE WITH RULE 6 OF
            REGULATION 7764. ABBREVIATED RULES FOR EACH RAFFLE WILL DISCLOSE AT
            LEAST: (I) START/END DATES; (II) ELIGIBILITY; (III)
            ORGANIZER/PROMOTER; (IV) “NO PURCHASE NECESSARY” WITH A FREE AMOE;
            (V) PRIZE/AWARD DESCRIPTION AND CONDITIONS; (VI) ENTRY METHOD(S);
            (VII) PRIZE DELIVERY/PAYMENT METHOD AND TIMING; (VIII) A LINK OR
            REFERENCE TO THESE FULL OFFICIAL RULES. ADVERTISING MUST NOT BE
            FALSE OR MISLEADING.
            <h6 className="fw-bold mt-4">11. CONDUCT AND DISQUALIFICATION</h6>
            ANY ATTEMPT TO COMMIT FRAUD, MANIPULATION, OR PARTICIPATION FROM
            OUTSIDE PUERTO RICO IS STRICTLY PROHIBITED. TICKET PLUS, INC.
            RESERVES THE RIGHT TO VOID TICKETS OR DISQUALIFY PARTICIPANTS
            ENGAGING IN MISCONDUCT OR ILLEGAL ACTIVITY, PURSUANT TO RULE 11 OF
            REGULATION 7764. ENTRIES THAT ARE FRAUDULENT, AUTOMATED, SUBMITTED
            FROM INELIGIBLE TERRITORIES, OR OTHERWISE IN VIOLATION OF THESE
            RULES ARE VOID. TICKET PLUS MAY DISQUALIFY ANY PARTICIPANT WHO
            TAMPERS WITH OR ATTEMPTS TO TAMPER WITH THE ENTRY PROCESS OR THE
            OPERATION OF THE RAFFLE; ACTS IN AN UNSPORTSMANLIKE OR DISRUPTIVE
            MANNER; OR VIOLATES THESE RULES. TICKET PLUS MAY CANCEL, MODIFY, OR
            SUSPEND THE RAFFLE IF A VIRUS, BUG, UNAUTHORIZED INTERVENTION,
            FRAUD, TECHNICAL FAILURE, HUMAN ERROR, OR ANY OTHER CAUSE CORRUPTS
            OR AFFECTS THE ADMINISTRATION, SECURITY, OR PROPER CONDUCT OF THE
            RAFFLE, SUBJECT TO APPLICABLE LAW.
            <h6 className="fw-bold mt-4">12. USE OF FUNDS</h6>
            FUNDS WILL BE DISTRIBUTED AS FOLLOWS: FIFTY PERCENT (50%) TO THE
            WINNER AND FIFTY PERCENT (50%) TO THE DESIGNATED NONPROFIT
            FOUNDATION. ADMINISTRATIVE EXPENSES SHALL NOT EXCEED TWENTY PERCENT
            (20%) OF THE GROSS FUND, IN ACCORDANCE WITH DACO AND LAW NO.
            465-1947.
            <h6 className="fw-bold mt-4">13. DATA PROTECTION</h6>
            TICKET PLUS COLLECTS, USES, AND SAFEGUARDS PARTICIPANT INFORMATION
            IN ACCORDANCE WITH ITS PRIVACY POLICY AND APPLICABLE PUERTO RICO
            LAW. TICKET PLUS, INC. WILL SAFEGUARD PARTICIPANT INFORMATION IN
            ACCORDANCE WITH RULE 7(B) OF REGULATION 9158. NO PERSONAL DATA WILL
            BE SHARED WITHOUT EXPRESS CONSENT. BY ENTERING, PARTICIPANTS CONSENT
            TO THE COLLECTION AND USE OF THEIR PERSONAL INFORMATION FOR THE
            ADMINISTRATION OF THE RAFFLE AND FOR COMMUNICATIONS AS DESCRIBED IN
            THESE RULES AND THE PRIVACY POLICY.
            <h6 className="fw-bold mt-4">14. CLAIMS & JURISDICTION</h6>
            PARTICIPANTS MAY FILE CLAIMS OR INQUIRIES USING THE CHANNELS
            INDICATED IN THE ABBREVIATED RULES AND ON THE WEBSITE. TO THE EXTENT
            PERMITTED BY LAW, DISPUTES WILL BE RESOLVED ON AN INDIVIDUAL BASIS
            WITHOUT RESORT TO CLASS ACTIONS, AND RECOVERY WILL BE LIMITED TO
            ACTUAL OUT-OF-POCKET EXPENSES. THESE RULES AND THE RAFFLE ARE
            GOVERNED BY THE LAWS OF PUERTO RICO, AND THE COURTS OF PUERTO RICO
            HAVE EXCLUSIVE JURISDICTION. ANY CLAIMS RELATED TO THIS RAFFLE MUST
            BE FILED BEFORE THE PUERTO RICO DEPARTMENT OF CONSUMER AFFAIRS
            (DACO). THIS RAFFLE IS GOVERNED EXCLUSIVELY BY THE LAWS AND COURTS
            OF THE COMMONWEALTH OF PUERTO RICO.
            <h6 className="fw-bold mt-4">15. CANCELLATION OR SUSPENSION</h6>
            THE RAFFLE MAY BE CANCELED OR SUSPENDED IN THE EVENT OF FORCE
            MAJEURE OR ANY IRREGULARITIES COMPROMISING ITS INTEGRITY, IN
            ACCORDANCE WITH RULE 9 OF REGULATION 7764. IN SUCH CASES THE EVENT
            WILL BE RESCHEDULED. IF THE RAFFLE CANNOT BE CONDUCTED AS PLANNED
            DUE TO CAUSES BEYOND CONTROL OR INTEGRITY CONCERNS, TICKET PLUS MAY
            MODIFY, SUSPEND, TERMINATE, OR CANCEL THE RAFFLE IN ACCORDANCE WITH
            APPLICABLE LAW AND ANY REQUIRED REGULATORY AUTHORIZATION OR
            NOTIFICATION. PARTICIPANTS WILL BE NOTIFIED THROUGH THE SAME
            CHANNELS WHERE THESE RULES WERE POSTED.
            <h6 className="fw-bold mt-4">
              16. CLAIMS, DISPUTES, REMEDIES, AND JURISDICTION
            </h6>
            PARTICIPANTS MAY FILE CLAIMS OR INQUIRIES USING THE CHANNELS
            INDICATED IN THE ABBREVIATED RULES AND ON THE WEBSITE. TO THE EXTENT
            PERMITTED BY LAW, DISPUTES WILL BE RESOLVED ON AN INDIVIDUAL BASIS
            WITHOUT RESORT TO CLASS ACTIONS, AND RECOVERY WILL BE LIMITED TO
            ACTUAL OUT-OF-POCKET EXPENSES. THESE RULES AND THE RAFFLE ARE
            GOVERNED BY THE LAWS OF PUERTO RICO, AND THE COURTS OF PUERTO RICO
            (AND, AS APPLICABLE, THE FEDERAL COURTS IN PUERTO RICO) HAVE
            EXCLUSIVE JURISDICTION.
            <h6 className="fw-bold mt-4">17. WINNERS LIST AND QUESTIONS</h6>A
            WINNERS LIST WILL BE MADE AVAILABLE UPON REQUEST VIA THE CONTACT
            INFORMATION STATED IN THE ABBREVIATED RULES OR WEBSITE. QUESTIONS,
            COMPLAINTS, OR REQUESTS FOR INFORMATION SHOULD BE DIRECTED TO THE
            SAME CONTACT CHANNELS.
            <h6 className="fw-bold mt-4">18. SEVERABILITY</h6>
            IF ANY PROVISION OF THESE RULES IS HELD INVALID OR UNENFORCEABLE,
            THE REMAINING PROVISIONS SHALL CONTINUE IN FULL FORCE AND EFFECT.
            TICKET PLUS MAY PUBLISH CORRECTIVE TERMS TO THE EXTENT PERMITTED BY
            LAW.
            <h6 className="fw-bold mt-4">19. LEGAL NOTICE</h6>
            PUBLISHING FALSE OR MISLEADING ADVERTISEMENTS IS ILLEGAL AND MAY
            RESULT IN ADMINISTRATIVE SANCTIONS OR FINES OF UP TO $10,000,
            PURSUANT TO LAW NO. 5 OF 1973.
          </div>
        </div>
      </div>
    </div>
  );
};

export default Rules;
